# Generated by Django 6.1.1 on 2026-09-12 02:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('category', models.CharField(choices=[('TRAVEL', 'Travel'), ('MEALS', 'Meals'), ('SUPPLIES', 'Supplies'), ('TAXI', 'Taxi'), ('ACCOMMODATION', 'Accommodation'), ('OTHER', 'Other')], max_length=30)),
                ('merchant', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('expense_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('receipt_text', models.TextField(blank=True)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='DRAFT', max_length=20)),
                ('ai_extracted', models.BooleanField(default=False)),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('duplicate_flag', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='possible_duplicates', to='claims.expenseclaim')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
