# Generated by Django 6.1.1 on 2026-09-15 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseclaim',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='expenseclaim',
            name='category',
            field=models.CharField(choices=[('TRAVEL', 'Travel'), ('MEALS', 'Meals'), ('SUPPLIES', 'Supplies'), ('TAXI', 'Taxi'), ('ACCOMMODATION', 'Accommodation'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.AlterField(
            model_name='expenseclaim',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='expenseclaim',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_claims', to='claims.expenseclaim'),
        ),
        migrations.AlterField(
            model_name='expenseclaim',
            name='receipt_image',
            field=models.ImageField(default='', upload_to='receipts/%Y/%m/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expenseclaim',
            name='receipt_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
