# Generated by Django 6.1.1 on 2026-09-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_alter_expenseclaim_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseclaim',
            name='receipt_image',
            field=models.FileField(upload_to='receipts/%Y/%m/'),
        ),
    ]
